{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bce8eb82",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "import streamlit as st\n",
    "import re\n",
    "import string\n",
    "import nltk\n",
    "import spacy\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "tf1 = TfidfVectorizer()\n",
    "\n",
    "model_filename = 'svm_model.pkl'\n",
    "with open(model_filename, 'rb') as model_file:\n",
    "    model = pickle.load(model_file)\n",
    "\n",
    "stopwords = nltk.corpus.stopwords.words('english')\n",
    "    \n",
    "def clean_text(text):\n",
    "    text = text.lower()\n",
    "    return text.strip()\n",
    "\n",
    "def remove_punctuation(text):\n",
    "    punctuation_free = \"\".join([i for i in text if i not in string.punctuation])\n",
    "    return punctuation_free\n",
    "\n",
    "def tokenization(text):\n",
    "    tokens = re.split(' ', text)\n",
    "    return tokens\n",
    "\n",
    "def remove_stopwords(text):\n",
    "    stopwords = nltk.corpus.stopwords.words('english')\n",
    "    output = \" \".join(i for i in text if i not in stopwords)\n",
    "    return output\n",
    "\n",
    "def lemmatizer(text):\n",
    "    nlp = spacy.load('en_core_web_sm')\n",
    "    doc = nlp(text)\n",
    "    sent = [token.lemma_ for token in doc if not token.text in set(stopwords)]\n",
    "    return ' '.join(sent)\n",
    "\n",
    "def preprocess_text(text):\n",
    "    text = clean_text(text)\n",
    "    text = remove_punctuation(text)\n",
    "    text = text.lower()\n",
    "    text = tokenization(text)\n",
    "    text = remove_stopwords(text)\n",
    "    text = lemmatizer(text)\n",
    "    return text\n",
    "\n",
    "st.title(\"Sentiment Analysis with SVM Model\")\n",
    "\n",
    "st.write(\"Enter a review text, and the model will predict its sentiment (e.g., positive or negative).\")\n",
    "\n",
    "input_text = st.text_area(\"Enter a review:\", \"\")\n",
    "\n",
    "if st.button(\"Predict\"):\n",
    "    if input_text:\n",
    "        preprocessed_text = preprocess_text(input_text)\n",
    "        text_vectorized = tf1.fit_transform([preprocessed_text])\n",
    "        prediction = model.predict(text_vectorized)\n",
    "        sentiment = \"Positive\" if prediction == 1 else \"Negative\"\n",
    "        st.write(\"Sentiment:\", sentiment)\n",
    "    else:\n",
    "        st.write(\"Please enter a review text.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "aa97c570",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Streamlit version: 1.20.0\n",
      "Pillow version: 9.4.0\n",
      "Python re (regular expressions) version: 2.2.1\n",
      "NLTK version: 3.8.1\n",
      "spaCy version: 3.6.1\n",
      "scikit-learn version: 1.2.2\n",
      "joblib version: 1.2.0\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from PIL import Image\n",
    "import re\n",
    "import string\n",
    "import nltk\n",
    "import spacy\n",
    "import sklearn\n",
    "import joblib\n",
    "\n",
    "# Check the version of Streamlit\n",
    "print(f\"Streamlit version: {st.__version__}\")\n",
    "\n",
    "# Check the version of PIL (Pillow)\n",
    "pillow_version = Image.__version__\n",
    "print(f\"Pillow version: {pillow_version}\")\n",
    "\n",
    "# Check the version of re (regular expressions)\n",
    "print(f\"Python re (regular expressions) version: {re.__version__}\")\n",
    "\n",
    "# Check the version of NLTK (Natural Language Toolkit)\n",
    "nltk_version = nltk.__version__\n",
    "print(f\"NLTK version: {nltk_version}\")\n",
    "\n",
    "# Check the version of spaCy\n",
    "spacy_version = spacy.__version__\n",
    "print(f\"spaCy version: {spacy_version}\")\n",
    "\n",
    "# Check the version of scikit-learn\n",
    "sklearn_version = sklearn.__version__\n",
    "print(f\"scikit-learn version: {sklearn_version}\")\n",
    "\n",
    "# Check the version of joblib\n",
    "joblib_version = joblib.__version__\n",
    "print(f\"joblib version: {joblib_version}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2855a165",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
